services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VUE_APP_API_URL=${VUE_APP_API_URL}
        - VUE_APP_API_KEY=${VUE_APP_API_KEY}
        - VUE_APP_API_SECRET=${VUE_APP_API_SECRET}
    ports:
      - 8080:80
